dist: trusty
language: ruby
cache: bundler
before_install:
- bundle -v
- rm -f Gemfile.lock
- gem update --system
- gem --version
- bundle -v
script:
- bundle exec $CHECK
rvm:
- 2.4.1
matrix:
  fast_finish: true
  include:
  - env: CHECK='rubocop'
  - env: CHECK='rspec spec'
branches:
  only:
  - master
  - "/^v\\d/"
  - release